<a href="https://colab.research.google.com/github/bhakya01/Motor-Vehicle-Collisions---Crashes/blob/main/motorvehicle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MOTOR VEHICLE

# Objective:

The main objective of this project is to analyze motor vehicle crash data to identify accident patterns, major contributing factors, high-risk locations, and the severity of road accidents. Using Python, Pandas, Matplotlib, and Seaborn, the project aims to transform raw crash data into meaningful insights that can help improve road safety and reduce accidents, injuries, and fatalities.

# Upload and Load the csv file

In [ ]:
from google.colab import files

uploaded = files.upload()
import pandas as pd

df = pd.read_csv("Motor Vehicle.csv")
df

Saving Motor Vehicle.csv to Motor Vehicle (5).csv

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,10-05-2024,12:40,NaN,NaN,40.642540,-73.876520,"(40.64254, -73.87652)",BELT PARKWAY,NaN,NaN,...,0,Unspecified,Unspecified,NaN,4761266,Bike,E-Bike,NaN,NaN,NaN
1,10-05-2024,09:30,QUEENS,11691.0,40.598660,-73.753006,"(40.59866, -73.753006)",NaN,NaN,327 BEACH 19 ST,...,0,Unspecified,NaN,NaN,4803256,Ambulance,NaN,NaN,NaN,NaN
2,10-05-2024,13:43,NaN,NaN,NaN,NaN,NaN,MENAHAN STREET,NaN,NaN,...,0,Driver Inattention/Distraction,Unspecified,NaN,4761112,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
3,10-05-2024,06:05,NaN,NaN,NaN,NaN,NaN,WESTCHESTER SQUARE,NaN,NaN,...,0,Driver Inattention/Distraction,NaN,NaN,4761546,Sedan,NaN,NaN,NaN,NaN
4,10-05-2024,08:40,NaN,NaN,40.651268,-73.971810,"(40.651268, -73.97181)",PARK CIRCLE,NaN,NaN,...,0,Unspecified,NaN,NaN,4699637,Sedan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20642,07-11-2025,20:00,QUEENS,11435.0,40.709950,-73.809310,"(40.70995, -73.80931)",NaN,NaN,85-49 149 ST,...,0,Unspecified,NaN,NaN,4827623,Sedan,NaN,NaN,NaN,NaN
20643,09-10-2024,03:00,NaN,NaN,NaN,NaN,NaN,PEDESTRIAN WAY,YELLOWSTONE BOULEVARD,NaN,...,0,Driver Inattention/Distraction,Unspecified,NaN,4758908,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
20644,07-04-2025,01:40,QUEENS,11691.0,40.595870,-73.765564,"(40.59587, -73.765564)",BEACH 33 ST,SEAGIRT BLVD,NaN,...,0,Unsafe Speed,NaN,NaN,4825161,Sedan,NaN,NaN,NaN,NaN
20645,12-02-2025,22:00,NaN,NaN,40.660600,-74.001274,"(40.6606, -74.001274)",GOWANUS EXPY (BQE),NaN,NaN,...,0,Unspecified,NaN,NaN,4861673,Sedan,NaN,NaN,NaN,NaN
20646,01-03-2026,14:35,NaN,NaN,40.613560,-74.038760,"(40.61356, -74.03876)",BELT PARKWAY,NaN,NaN,...,0,Steering Failure,NaN,NaN,4869308,Sedan,NaN,NaN,NaN,NaN

# Display dataset information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20647 entries, 0 to 20646
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH DATE                     20647 non-null  object
 1   CRASH TIME                     20647 non-null  object
 2   BOROUGH                        14243 non-null  object
 3   ZIP CODE                       14239 non-null  float64
 4   LATITUDE                       19313 non-null  float64
 5   LONGITUDE                      19313 non-null  float64
 6   LOCATION                       19313 non-null  object
 7   ON STREET NAME                 14776 non-null  object
 8   CROSS STREET NAME              10105 non-null  object
 9   OFF STREET NAME                5871 non-null   object
 10  NUMBER OF PERSONS INJURED      20647 non-null  int64
 11  NUMBER OF PERSONS KILLED       20647 non-null  int64
 12  NUMBER OF PEDESTRIANS INJURED  20647 non-null  int64
 13  NUMBER OF CYCLIST INJURED      20647 non-null  int64
 14  NUMBER OF MOTORIST INJURED     20647 non-null  int64
 15  NUMBER OF MOTORIST KILLED      20647 non-null  int64
 16  CONTRIBUTING FACTOR VEHICLE 1  20503 non-null  object
 17  CONTRIBUTING FACTOR VEHICLE 2  15745 non-null  object
 18  VEHICLE TYPE CODE 2            152 non-null    object
 19  VEHICLE TYPE CODE 3            20647 non-null  int64
 20  VEHICLE TYPE CODE 4            20326 non-null  object
 21  Unnamed: 21                    13616 non-null  object
 22  Unnamed: 22                    1706 non-null   object
 23  Unnamed: 23                    479 non-null    object
 24  Unnamed: 24                    149 non-null    object
dtypes: float64(3), int64(7), object(15)
memory usage: 3.9+ MB

# Check data types of each column

In [ ]:
df.dtypes

CRASH DATE                        object
CRASH TIME                        object
BOROUGH                           object
ZIP CODE                         float64
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
ON STREET NAME                    object
CROSS STREET NAME                 object
OFF STREET NAME                   object
NUMBER OF PERSONS INJURED          int64
NUMBER OF PERSONS KILLED           int64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
CONTRIBUTING FACTOR VEHICLE 1     object
CONTRIBUTING FACTOR VEHICLE 2     object
VEHICLE TYPE CODE 2               object
VEHICLE TYPE CODE 3                int64
VEHICLE TYPE CODE 4               object
Unnamed: 21                       object
Unnamed: 22                       object
Unnamed: 23                       object
Unnamed: 24                       object
dtype: object

# Generate descriptive statistics

In [ ]:
display(df.describe(include="all"))

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
count,20647,20647,14243,14239.000000,19313.000000,19313.000000,19313,14776,10105,5871,...,20647.000000,20503,15745,152,2.064700e+04,20326,13616,1706,479,149
unique,148,1430,5,NaN,NaN,NaN,14723,2522,2716,5594,...,NaN,51,42,4,NaN,157,160,39,14,8
top,03-08-2024,00:00,BROOKLYN,NaN,NaN,NaN,"(0.0, 0.0)",BELT PARKWAY,BROADWAY,FLATBUSH AVENUE EXTENSION,...,NaN,Unspecified,Unspecified,Unspecified,NaN,Sedan,Sedan,Sedan,Sedan,Sedan
freq,311,373,5018,NaN,NaN,NaN,40,300,116,6,...,NaN,5080,13291,142,NaN,9332,5386,823,232,76
mean,NaN,NaN,NaN,10893.363579,40.636330,-73.767321,NaN,NaN,NaN,NaN,...,0.001162,NaN,NaN,NaN,4.716353e+06,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,525.883547,1.853110,3.361814,NaN,NaN,NaN,NaN,...,0.046150,NaN,NaN,NaN,1.635452e+04,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,10000.000000,0.000000,-74.248060,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.691606e+06,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,10456.000000,40.662975,-73.969790,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.702042e+06,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,11208.000000,40.712757,-73.923510,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.715825e+06,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,11237.000000,40.770412,-73.870010,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.730122e+06,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,11697.000000,40.910202,0.000000,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,4.890397e+06,NaN,NaN,NaN,NaN,NaN

# Display Head 10 rows

---

In [ ]:
df.head(10)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,10-05-2024,12:40,NaN,NaN,40.642540,-73.876520,"(40.64254, -73.87652)",BELT PARKWAY,NaN,NaN,...,0,Unspecified,Unspecified,NaN,4761266,Bike,E-Bike,NaN,NaN,NaN
1,10-05-2024,09:30,QUEENS,11691.0,40.598660,-73.753006,"(40.59866, -73.753006)",NaN,NaN,327 BEACH 19 ST,...,0,Unspecified,NaN,NaN,4803256,Ambulance,NaN,NaN,NaN,NaN
2,10-05-2024,13:43,NaN,NaN,NaN,NaN,NaN,MENAHAN STREET,NaN,NaN,...,0,Driver Inattention/Distraction,Unspecified,NaN,4761112,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
3,10-05-2024,06:05,NaN,NaN,NaN,NaN,NaN,WESTCHESTER SQUARE,NaN,NaN,...,0,Driver Inattention/Distraction,NaN,NaN,4761546,Sedan,NaN,NaN,NaN,NaN
4,10-05-2024,08:40,NaN,NaN,40.651268,-73.971810,"(40.651268, -73.97181)",PARK CIRCLE,NaN,NaN,...,0,Unspecified,NaN,NaN,4699637,Sedan,NaN,NaN,NaN,NaN
5,10-05-2024,21:40,NaN,NaN,40.825030,-73.931220,"(40.82503, -73.93122)",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,0,Unsafe Speed,Unspecified,NaN,4721677,Tanker,PICK-UP,NaN,NaN,NaN
6,10-05-2024,12:40,BRONX,10458.0,40.868706,-73.884710,"(40.868706, -73.88471)",BEDFORD PARK BLVD,MARION AVE,NaN,...,0,Unspecified,NaN,NaN,4804525,Sedan,NaN,NaN,NaN,NaN
7,10-05-2024,06:00,BRONX,10463.0,40.875100,-73.911710,"(40.8751, -73.91171)",NaN,NaN,135 W 225 ST,...,0,Unsafe Speed,NaN,NaN,4804466,Sedan,NaN,NaN,NaN,NaN
8,10-05-2024,10:56,NaN,NaN,NaN,NaN,NaN,DELONG STREET,NaN,NaN,...,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,NaN,4761109,Sedan,Sedan,NaN,NaN,NaN
9,10-05-2024,16:30,NaN,NaN,NaN,NaN,NaN,BELT PARKWAY RAMP,NaN,NaN,...,0,Unspecified,NaN,NaN,4722033,Sedan,NaN,NaN,NaN,NaN